### ISSUE TITLE
Save Customer Data

### ISSUE THREAD

**Issue by Arceoavs** [Arceoavs/emtour#1]
- receiving the data from the customer: emTour process has begun event

**Comment by Arceoavs** [comment]
Hey you did everything wrong here!

**Comment by DanielDominic** [comment]
Post: http://localhost:8080/emtourrequest/recommendation
{
    "email": "ddj97@live.de",
    "firstname": "Daniel",
    "lastname": "Dominic",
    "phone": "12345",
    "address": "address1",
    "earliest_departure": "02-03-2020",
    "latest_return": "11-03-2020",
    "length_of_travel": "6",
    "cheapest_flight": "true",
    "no_of_adults": "2",
    "no_of_children": "2",
    "customer_age": [
        "30",
        "29",
        "4",
        "6"
    ],
    "type_of_travel": "train",
    "travel_distance": "200",
    "travel_time": "4",
    "weather_preferences": [
        "Sunny",
        "Moody"
    ],
    "food_preferences": [
        "Spicy",
        "Bread"
    ],
    "service_lvl": "budget",
    "accommodation_type": "Hotel",
    "outdoor/indoor/both": "indoor",
    "fitness/relaxed/both": "fitness",
    "adventurous/reserved/both": "both",
    "group/individual/both": "individual",
    "allergies": [
        "mushrooms"
    ],
    "phobias": [
        "mushrooms"
    ],
    "diseases": [],
    "budget": "20"
}
