### ISSUE TITLE
Check out timer events

### ISSUE THREAD

**Issue by Arceoavs** [Arceoavs/emtour#9]
These were needed for the initial model already

**Comment by DanielDominic** [comment]
Time durations are apparently defined by the ISO 8601 Durations format:
Wiki:
_Durations define the amount of intervening time in a time interval and are represented by the format P[n]Y[n]M[n]DT[n]H[n]M[n]S or P[n]W as shown to the right. In these representations, the [n] is replaced by the value for each of the date and time elements that follow the [n]. Leading zeros are not required, but the maximum number of digits for each element should be agreed to by the communicating parties. The capital letters P, Y, M, W, D, T, H, M, and S are designators for each of the date and time elements and are not replaced.

P is the duration designator (for period) placed at the start of the duration representation.
Y is the year designator that follows the value for the number of years.
M is the month designator that follows the value for the number of months.
W is the week designator that follows the value for the number of weeks.
D is the day designator that follows the value for the number of days._
-----
One month is, therefore: "P1W"
